# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
#  docker-compose -f docker-compose.yml up
# Add the `-d` flag at the end for detached execution
version: "3"
#  angular-docker-service:
#    image: khimin1719/ui:v1
#    networks: ['backend']
#    build:
#      dockerfile: ./Dockerfile
#    ports:
#      - "4200:4200"
services:
  auth:
    image: khimin1719/auth:v1
    networks: ['backend']
    build:
      context: ./
      dockerfile: ./DContract/docker/Dockerfile
    volumes:
      - /data/auth
    ports:
      - "8080:8080"
  ui:
    image: khimin1719/ui:v1
    networks: ['backend']
    build:
      context: ./
      dockerfile: ./incorp_ui/docker/Dockerfile
    volumes:
      - /data/ui
    ports:
      - "4200:4200"
networks: {backend: {}}
